# Generated by Django 5.0.6 on 2024-06-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('discription', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
