# Generated by Django 5.0.6 on 2024-06-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0002_seminars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seminars',
        ),
    ]
