# Generated by Django 5.0.6 on 2024-06-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0003_delete_seminars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('description', models.TextField()),
            ],
        ),
    ]
