# Generated by Django 5.0.6 on 2024-06-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0004_seminars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
