# Generated by Django 5.0.6 on 2024-06-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0005_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('title', models.TextField()),
                ('discription', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
