# Generated by Django 5.0.6 on 2024-06-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0006_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('fblink', models.URLField()),
                ('lnlink', models.URLField()),
                ('iglink', models.URLField()),
            ],
        ),
    ]
