# Generated by Django 5.0.6 on 2024-06-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
