# Generated by Django 5.0.6 on 2024-06-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0010_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
