# Generated by Django 5.0.6 on 2024-06-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0012_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
