# Generated by Django 5.0.6 on 2024-06-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0013_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('maindate', models.DateField()),
                ('title', models.TextField()),
                ('discription', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
