# Generated by Django 5.0.6 on 2024-07-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0014_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
