# Generated by Django 5.0.6 on 2024-07-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0016_oldsharktank_sharktank'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventsUpcoming',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.TextField()),
                ('discription', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('Formurl', models.URLField()),
            ],
        ),
    ]
