# Generated by Django 5.0.6 on 2024-07-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0017_eventsupcoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
