# Generated by Django 5.0.6 on 2024-07-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0018_profile_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fblink',
            new_name='gitlink',
        ),
    ]
